before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

language: node_js
node_js:
  - node

cache: npm

script:
  - npm install
  - npm run test

after_success:
  - .\node_modules\.bin\nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)
