before_script: 'sudo aptitude -y -q install libcairo2-dev ffmpeg libpixman-1-dev libpango1.0-dev libgif-dev libjpeg-dev libgtk2.0-dev vlc libvlc-dev portaudio19-dev libsqlite3-dev libcurl4-openssl-dev makeself curl'

language: node_js
node_js:
  - node

cache: npm

script:
  - npm install
  - npm run test

after_success:
  - .\node_modules\.bin\nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)
